export const CAT_BREEDS = [
  // Breed classes from the model
  "Abyssinian",
  "American Curl",
  "American Shorthair",
  "Balinese",
  "Bengal",
  "Birman",
  "Bombay",
  "British Shorthair",
  "Burmese",
  "Cornish Rex",
  "Devon Rex",
  "Egyptian Mau",
  "Exotic Shorthair",
  "Extra-Toes Cat - Hemingway Polydactyl",
  "Havana",
  "Himalayan",
  "Japanese Bobtail",
  "Korat",
  "Maine Coon",
  "Manx",
  "Nebelung",
  "Norwegian Forest Cat",
  "Oriental Short Hair",
  "Persian",
  "Ragdoll",
  "Russian Blue",
  "Scottish Fold",
  "Selkirk Rex",
  "Siamese",
  "Siberian",
  "Snowshoe",
  "Sphynx",
  "Tonkinese",
  "Toyger tiger cat",
  "Turkish Angora",

  // Additional breeds for user selection
  "Mixed Breed",
  "Unknown",
] as const;

export type CatBreed = typeof CAT_BREEDS[number];